/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysOffice;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRoleOffice;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jeesite extends SchemaImpl {

    private static final long serialVersionUID = -177747013;

    /**
     * The reference instance of <code>jeesite</code>
     */
    public static final Jeesite JEESITE = new Jeesite();

    /**
     * 区域表
     */
    public final SysArea SYS_AREA = SysArea.SYS_AREA;

    /**
     * 字典表
     */
    public final SysDict SYS_DICT = SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public final SysLog SYS_LOG = SysLog.SYS_LOG;

    /**
     * 菜单表
     */
    public final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * 机构表
     */
    public final SysOffice SYS_OFFICE = SysOffice.SYS_OFFICE;

    /**
     * 角色表
     */
    public final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 角色-菜单
     */
    public final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 角色-机构
     */
    public final SysRoleOffice SYS_ROLE_OFFICE = SysRoleOffice.SYS_ROLE_OFFICE;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * 用户-角色
     */
    public final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Jeesite() {
        super("jeesite", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysArea.SYS_AREA,
            SysDict.SYS_DICT,
            SysLog.SYS_LOG,
            SysMenu.SYS_MENU,
            SysOffice.SYS_OFFICE,
            SysRole.SYS_ROLE,
            SysRoleMenu.SYS_ROLE_MENU,
            SysRoleOffice.SYS_ROLE_OFFICE,
            SysUser.SYS_USER,
            SysUserRole.SYS_USER_ROLE);
    }
}
