/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysOffice;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRoleOffice;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;
import com.yueya.system.dao.tables.records.SysAreaRecord;
import com.yueya.system.dao.tables.records.SysDictRecord;
import com.yueya.system.dao.tables.records.SysLogRecord;
import com.yueya.system.dao.tables.records.SysMenuRecord;
import com.yueya.system.dao.tables.records.SysOfficeRecord;
import com.yueya.system.dao.tables.records.SysRoleMenuRecord;
import com.yueya.system.dao.tables.records.SysRoleOfficeRecord;
import com.yueya.system.dao.tables.records.SysRoleRecord;
import com.yueya.system.dao.tables.records.SysUserRecord;
import com.yueya.system.dao.tables.records.SysUserRoleRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jeesite</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysAreaRecord> KEY_SYS_AREA_PRIMARY = UniqueKeys0.KEY_SYS_AREA_PRIMARY;
    public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_PRIMARY = UniqueKeys0.KEY_SYS_DICT_PRIMARY;
    public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = UniqueKeys0.KEY_SYS_LOG_PRIMARY;
    public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = UniqueKeys0.KEY_SYS_MENU_PRIMARY;
    public static final UniqueKey<SysOfficeRecord> KEY_SYS_OFFICE_PRIMARY = UniqueKeys0.KEY_SYS_OFFICE_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_MENU_PRIMARY;
    public static final UniqueKey<SysRoleOfficeRecord> KEY_SYS_ROLE_OFFICE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_OFFICE_PRIMARY;
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = UniqueKeys0.KEY_SYS_USER_PRIMARY;
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<SysAreaRecord> KEY_SYS_AREA_PRIMARY = Internal.createUniqueKey(SysArea.SYS_AREA, "KEY_sys_area_PRIMARY", SysArea.SYS_AREA.ID);
        public static final UniqueKey<SysDictRecord> KEY_SYS_DICT_PRIMARY = Internal.createUniqueKey(SysDict.SYS_DICT, "KEY_sys_dict_PRIMARY", SysDict.SYS_DICT.ID);
        public static final UniqueKey<SysLogRecord> KEY_SYS_LOG_PRIMARY = Internal.createUniqueKey(SysLog.SYS_LOG, "KEY_sys_log_PRIMARY", SysLog.SYS_LOG.ID);
        public static final UniqueKey<SysMenuRecord> KEY_SYS_MENU_PRIMARY = Internal.createUniqueKey(SysMenu.SYS_MENU, "KEY_sys_menu_PRIMARY", SysMenu.SYS_MENU.ID);
        public static final UniqueKey<SysOfficeRecord> KEY_SYS_OFFICE_PRIMARY = Internal.createUniqueKey(SysOffice.SYS_OFFICE, "KEY_sys_office_PRIMARY", SysOffice.SYS_OFFICE.ID);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", SysRole.SYS_ROLE.ID);
        public static final UniqueKey<SysRoleMenuRecord> KEY_SYS_ROLE_MENU_PRIMARY = Internal.createUniqueKey(SysRoleMenu.SYS_ROLE_MENU, "KEY_sys_role_menu_PRIMARY", SysRoleMenu.SYS_ROLE_MENU.ROLE_ID, SysRoleMenu.SYS_ROLE_MENU.MENU_ID);
        public static final UniqueKey<SysRoleOfficeRecord> KEY_SYS_ROLE_OFFICE_PRIMARY = Internal.createUniqueKey(SysRoleOffice.SYS_ROLE_OFFICE, "KEY_sys_role_office_PRIMARY", SysRoleOffice.SYS_ROLE_OFFICE.ROLE_ID, SysRoleOffice.SYS_ROLE_OFFICE.OFFICE_ID);
        public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, "KEY_sys_user_PRIMARY", SysUser.SYS_USER.ID);
        public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, "KEY_sys_user_role_PRIMARY", SysUserRole.SYS_USER_ROLE.USER_ID, SysUserRole.SYS_USER_ROLE.ROLE_ID);
    }
}
