/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysOrganization;
import com.yueya.system.dao.tables.SysPermission;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRoleOrg;
import com.yueya.system.dao.tables.SysRolePermission;
import com.yueya.system.dao.tables.SysSystem;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pms extends SchemaImpl {

    private static final long serialVersionUID = 2023662092;

    /**
     * The reference instance of <code>pms</code>
     */
    public static final Pms PMS = new Pms();

    /**
     * 区域表
     */
    public final SysArea SYS_AREA = SysArea.SYS_AREA;

    /**
     * The table <code>pms.sys_dict</code>.
     */
    public final SysDict SYS_DICT = SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public final SysLog SYS_LOG = SysLog.SYS_LOG;

    /**
     * The table <code>pms.sys_menu</code>.
     */
    public final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * The table <code>pms.sys_organization</code>.
     */
    public final SysOrganization SYS_ORGANIZATION = SysOrganization.SYS_ORGANIZATION;

    /**
     * The table <code>pms.sys_permission</code>.
     */
    public final SysPermission SYS_PERMISSION = SysPermission.SYS_PERMISSION;

    /**
     * The table <code>pms.sys_role</code>.
     */
    public final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * The table <code>pms.sys_role_menu</code>.
     */
    public final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>pms.sys_role_org</code>.
     */
    public final SysRoleOrg SYS_ROLE_ORG = SysRoleOrg.SYS_ROLE_ORG;

    /**
     * The table <code>pms.sys_role_permission</code>.
     */
    public final SysRolePermission SYS_ROLE_PERMISSION = SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>pms.sys_system</code>.
     */
    public final SysSystem SYS_SYSTEM = SysSystem.SYS_SYSTEM;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * The table <code>pms.sys_user_role</code>.
     */
    public final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Pms() {
        super("pms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysArea.SYS_AREA,
            SysDict.SYS_DICT,
            SysLog.SYS_LOG,
            SysMenu.SYS_MENU,
            SysOrganization.SYS_ORGANIZATION,
            SysPermission.SYS_PERMISSION,
            SysRole.SYS_ROLE,
            SysRoleMenu.SYS_ROLE_MENU,
            SysRoleOrg.SYS_ROLE_ORG,
            SysRolePermission.SYS_ROLE_PERMISSION,
            SysSystem.SYS_SYSTEM,
            SysUser.SYS_USER,
            SysUserRole.SYS_USER_ROLE);
    }
}
