/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysOffice;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRoleOffice;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;


/**
 * Convenience access to all tables in jeesite
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 区域表
     */
    public static final SysArea SYS_AREA = SysArea.SYS_AREA;

    /**
     * 字典表
     */
    public static final SysDict SYS_DICT = SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public static final SysLog SYS_LOG = SysLog.SYS_LOG;

    /**
     * 菜单表
     */
    public static final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * 机构表
     */
    public static final SysOffice SYS_OFFICE = SysOffice.SYS_OFFICE;

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 角色-菜单
     */
    public static final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 角色-机构
     */
    public static final SysRoleOffice SYS_ROLE_OFFICE = SysRoleOffice.SYS_ROLE_OFFICE;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * 用户-角色
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;
}
