/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysPermission;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRolePermission;
import com.yueya.system.dao.tables.SysSystem;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;


/**
 * Convenience access to all tables in pms
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 区域表
     */
    public static final SysArea SYS_AREA = SysArea.SYS_AREA;

    /**
     * The table <code>pms.sys_dict</code>.
     */
    public static final SysDict SYS_DICT = SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public static final SysLog SYS_LOG = SysLog.SYS_LOG;

    /**
     * The table <code>pms.sys_menu</code>.
     */
    public static final SysMenu SYS_MENU = SysMenu.SYS_MENU;

    /**
     * The table <code>pms.sys_permission</code>.
     */
    public static final SysPermission SYS_PERMISSION = SysPermission.SYS_PERMISSION;

    /**
     * The table <code>pms.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * The table <code>pms.sys_role_menu</code>.
     */
    public static final SysRoleMenu SYS_ROLE_MENU = SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>pms.sys_role_permission</code>.
     */
    public static final SysRolePermission SYS_ROLE_PERMISSION = SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>pms.sys_system</code>.
     */
    public static final SysSystem SYS_SYSTEM = SysSystem.SYS_SYSTEM;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * The table <code>pms.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;
}
