/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao;


import com.yueya.system.dao.tables.SysArea;
import com.yueya.system.dao.tables.SysDict;
import com.yueya.system.dao.tables.SysLog;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysPermission;
import com.yueya.system.dao.tables.SysRole;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysRolePermission;
import com.yueya.system.dao.tables.SysSystem;
import com.yueya.system.dao.tables.SysUser;
import com.yueya.system.dao.tables.SysUserRole;


/**
 * Convenience access to all tables in pms
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 区域表
     */
    public static final SysArea SYS_AREA = com.yueya.system.dao.tables.SysArea.SYS_AREA;

    /**
     * The table <code>pms.sys_dict</code>.
     */
    public static final SysDict SYS_DICT = com.yueya.system.dao.tables.SysDict.SYS_DICT;

    /**
     * 日志表
     */
    public static final SysLog SYS_LOG = com.yueya.system.dao.tables.SysLog.SYS_LOG;

    /**
     * The table <code>pms.sys_menu</code>.
     */
    public static final SysMenu SYS_MENU = com.yueya.system.dao.tables.SysMenu.SYS_MENU;

    /**
     * The table <code>pms.sys_permission</code>.
     */
    public static final SysPermission SYS_PERMISSION = com.yueya.system.dao.tables.SysPermission.SYS_PERMISSION;

    /**
     * The table <code>pms.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = com.yueya.system.dao.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>pms.sys_role_menu</code>.
     */
    public static final SysRoleMenu SYS_ROLE_MENU = com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU;

    /**
     * The table <code>pms.sys_role_permission</code>.
     */
    public static final SysRolePermission SYS_ROLE_PERMISSION = com.yueya.system.dao.tables.SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>pms.sys_system</code>.
     */
    public static final SysSystem SYS_SYSTEM = com.yueya.system.dao.tables.SysSystem.SYS_SYSTEM;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = com.yueya.system.dao.tables.SysUser.SYS_USER;

    /**
     * The table <code>pms.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = com.yueya.system.dao.tables.SysUserRole.SYS_USER_ROLE;
}
