/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 区域表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAreaDO implements Serializable {

    private static final long serialVersionUID = -1200544251;

    private String    id;
    private String    parentId;
    private String    parentIds;
    private String    name;
    private Long      sort;
    private String    code;
    private String    type;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;
    private String    remarks;
    private String    delFlag;

    public SysAreaDO() {}

    public SysAreaDO(SysAreaDO value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.parentIds = value.parentIds;
        this.name = value.name;
        this.sort = value.sort;
        this.code = value.code;
        this.type = value.type;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysAreaDO(
        String    id,
        String    parentId,
        String    parentIds,
        String    name,
        Long      sort,
        String    code,
        String    type,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate,
        String    remarks,
        String    delFlag
    ) {
        this.id = id;
        this.parentId = parentId;
        this.parentIds = parentIds;
        this.name = name;
        this.sort = sort;
        this.code = code;
        this.type = type;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentIds() {
        return this.parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getSort() {
        return this.sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysAreaDO (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentIds);
        sb.append(", ").append(name);
        sb.append(", ").append(sort);
        sb.append(", ").append(code);
        sb.append(", ").append(type);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
