/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictDO implements Serializable {

    private static final long serialVersionUID = -1140965674;

    private String    id;
    private String    value;
    private String    label;
    private String    type;
    private String    description;
    private Long      sort;
    private String    parentId;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;
    private String    remarks;
    private String    delFlag;

    public SysDictDO() {}

    public SysDictDO(SysDictDO value) {
        this.id = value.id;
        this.value = value.value;
        this.label = value.label;
        this.type = value.type;
        this.description = value.description;
        this.sort = value.sort;
        this.parentId = value.parentId;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysDictDO(
        String    id,
        String    value,
        String    label,
        String    type,
        String    description,
        Long      sort,
        String    parentId,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate,
        String    remarks,
        String    delFlag
    ) {
        this.id = id;
        this.value = value;
        this.label = label;
        this.type = type;
        this.description = description;
        this.sort = sort;
        this.parentId = parentId;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getSort() {
        return this.sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDictDO (");

        sb.append(id);
        sb.append(", ").append(value);
        sb.append(", ").append(label);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(sort);
        sb.append(", ").append(parentId);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
