/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuDO implements Serializable {

    private static final long serialVersionUID = -240026875;

    private String    id;
    private String    parentId;
    private String    parentIds;
    private String    name;
    private Long      sort;
    private String    href;
    private String    target;
    private String    icon;
    private String    isShow;
    private String    permission;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;
    private String    remarks;
    private String    delFlag;

    public SysMenuDO() {}

    public SysMenuDO(SysMenuDO value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.parentIds = value.parentIds;
        this.name = value.name;
        this.sort = value.sort;
        this.href = value.href;
        this.target = value.target;
        this.icon = value.icon;
        this.isShow = value.isShow;
        this.permission = value.permission;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysMenuDO(
        String    id,
        String    parentId,
        String    parentIds,
        String    name,
        Long      sort,
        String    href,
        String    target,
        String    icon,
        String    isShow,
        String    permission,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate,
        String    remarks,
        String    delFlag
    ) {
        this.id = id;
        this.parentId = parentId;
        this.parentIds = parentIds;
        this.name = name;
        this.sort = sort;
        this.href = href;
        this.target = target;
        this.icon = icon;
        this.isShow = isShow;
        this.permission = permission;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentIds() {
        return this.parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getSort() {
        return this.sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public String getHref() {
        return this.href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIsShow() {
        return this.isShow;
    }

    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenuDO (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentIds);
        sb.append(", ").append(name);
        sb.append(", ").append(sort);
        sb.append(", ").append(href);
        sb.append(", ").append(target);
        sb.append(", ").append(icon);
        sb.append(", ").append(isShow);
        sb.append(", ").append(permission);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
