/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganizationDO implements Serializable {

    private static final long serialVersionUID = -101714588;

    private Long      id;
    private String    name;
    private String    parentId;
    private String    parentIds;
    private Long      areaId;
    private String    type;
    private String    level;
    private Timestamp gmtCreate;
    private Timestamp gmtModified;
    private String    defFlag;

    public SysOrganizationDO() {}

    public SysOrganizationDO(SysOrganizationDO value) {
        this.id = value.id;
        this.name = value.name;
        this.parentId = value.parentId;
        this.parentIds = value.parentIds;
        this.areaId = value.areaId;
        this.type = value.type;
        this.level = value.level;
        this.gmtCreate = value.gmtCreate;
        this.gmtModified = value.gmtModified;
        this.defFlag = value.defFlag;
    }

    public SysOrganizationDO(
        Long      id,
        String    name,
        String    parentId,
        String    parentIds,
        Long      areaId,
        String    type,
        String    level,
        Timestamp gmtCreate,
        Timestamp gmtModified,
        String    defFlag
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.parentIds = parentIds;
        this.areaId = areaId;
        this.type = type;
        this.level = level;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.defFlag = defFlag;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getParentIds() {
        return this.parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    public Long getAreaId() {
        return this.areaId;
    }

    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public Timestamp getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Timestamp getGmtModified() {
        return this.gmtModified;
    }

    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getDefFlag() {
        return this.defFlag;
    }

    public void setDefFlag(String defFlag) {
        this.defFlag = defFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysOrganizationDO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);
        sb.append(", ").append(parentIds);
        sb.append(", ").append(areaId);
        sb.append(", ").append(type);
        sb.append(", ").append(level);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(defFlag);

        sb.append(")");
        return sb.toString();
    }
}
