/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleDO implements Serializable {

    private static final long serialVersionUID = -291700591;

    private ULong     id;
    private String    name;
    private String    enName;
    private String    roleType;
    private String    sort;
    private String    remarks;
    private Timestamp gmtCreate;
    private Timestamp gmtModified;
    private String    delFlag;

    public SysRoleDO() {}

    public SysRoleDO(SysRoleDO value) {
        this.id = value.id;
        this.name = value.name;
        this.enName = value.enName;
        this.roleType = value.roleType;
        this.sort = value.sort;
        this.remarks = value.remarks;
        this.gmtCreate = value.gmtCreate;
        this.gmtModified = value.gmtModified;
        this.delFlag = value.delFlag;
    }

    public SysRoleDO(
        ULong     id,
        String    name,
        String    enName,
        String    roleType,
        String    sort,
        String    remarks,
        Timestamp gmtCreate,
        Timestamp gmtModified,
        String    delFlag
    ) {
        this.id = id;
        this.name = name;
        this.enName = enName;
        this.roleType = roleType;
        this.sort = sort;
        this.remarks = remarks;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.delFlag = delFlag;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEnName() {
        return this.enName;
    }

    public void setEnName(String enName) {
        this.enName = enName;
    }

    public String getRoleType() {
        return this.roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getSort() {
        return this.sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Timestamp getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Timestamp getGmtModified() {
        return this.gmtModified;
    }

    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleDO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(enName);
        sb.append(", ").append(roleType);
        sb.append(", ").append(sort);
        sb.append(", ").append(remarks);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
