/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuDO implements Serializable {

    private static final long serialVersionUID = -503667615;

    private Long id;
    private Long menuId;
    private Long roleId;

    public SysRoleMenuDO() {}

    public SysRoleMenuDO(SysRoleMenuDO value) {
        this.id = value.id;
        this.menuId = value.menuId;
        this.roleId = value.roleId;
    }

    public SysRoleMenuDO(
        Long id,
        Long menuId,
        Long roleId
    ) {
        this.id = id;
        this.menuId = menuId;
        this.roleId = roleId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleMenuDO (");

        sb.append(id);
        sb.append(", ").append(menuId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
