/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleOrgDO implements Serializable {

    private static final long serialVersionUID = 1375816729;

    private Long roleId;
    private Long orgId;

    public SysRoleOrgDO() {}

    public SysRoleOrgDO(SysRoleOrgDO value) {
        this.roleId = value.roleId;
        this.orgId = value.orgId;
    }

    public SysRoleOrgDO(
        Long roleId,
        Long orgId
    ) {
        this.roleId = roleId;
        this.orgId = orgId;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getOrgId() {
        return this.orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleOrgDO (");

        sb.append(roleId);
        sb.append(", ").append(orgId);

        sb.append(")");
        return sb.toString();
    }
}
