/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * 角色-机构
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleOfficeDO implements Serializable {

    private static final long serialVersionUID = -1841255101;

    private String roleId;
    private String officeId;

    public SysRoleOfficeDO() {}

    public SysRoleOfficeDO(SysRoleOfficeDO value) {
        this.roleId = value.roleId;
        this.officeId = value.officeId;
    }

    public SysRoleOfficeDO(
        String roleId,
        String officeId
    ) {
        this.roleId = roleId;
        this.officeId = officeId;
    }

    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getOfficeId() {
        return this.officeId;
    }

    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleOfficeDO (");

        sb.append(roleId);
        sb.append(", ").append(officeId);

        sb.append(")");
        return sb.toString();
    }
}
