/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRolePermissionDO implements Serializable {

    private static final long serialVersionUID = 170751537;

    private Long roleId;
    private Long permissionId;
    private Long id;

    public SysRolePermissionDO() {}

    public SysRolePermissionDO(SysRolePermissionDO value) {
        this.roleId = value.roleId;
        this.permissionId = value.permissionId;
        this.id = value.id;
    }

    public SysRolePermissionDO(
        Long roleId,
        Long permissionId,
        Long id
    ) {
        this.roleId = roleId;
        this.permissionId = permissionId;
        this.id = id;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRolePermissionDO (");

        sb.append(roleId);
        sb.append(", ").append(permissionId);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
