/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleDO implements Serializable {

    private static final long serialVersionUID = -397888979;

    private String    id;
    private String    officeId;
    private String    name;
    private String    enname;
    private String    roleType;
    private String    dataScope;
    private String    isSys;
    private String    useable;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;
    private String    remarks;
    private String    delFlag;

    public SysRoleDO() {}

    public SysRoleDO(SysRoleDO value) {
        this.id = value.id;
        this.officeId = value.officeId;
        this.name = value.name;
        this.enname = value.enname;
        this.roleType = value.roleType;
        this.dataScope = value.dataScope;
        this.isSys = value.isSys;
        this.useable = value.useable;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysRoleDO(
        String    id,
        String    officeId,
        String    name,
        String    enname,
        String    roleType,
        String    dataScope,
        String    isSys,
        String    useable,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate,
        String    remarks,
        String    delFlag
    ) {
        this.id = id;
        this.officeId = officeId;
        this.name = name;
        this.enname = enname;
        this.roleType = roleType;
        this.dataScope = dataScope;
        this.isSys = isSys;
        this.useable = useable;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOfficeId() {
        return this.officeId;
    }

    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEnname() {
        return this.enname;
    }

    public void setEnname(String enname) {
        this.enname = enname;
    }

    public String getRoleType() {
        return this.roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getDataScope() {
        return this.dataScope;
    }

    public void setDataScope(String dataScope) {
        this.dataScope = dataScope;
    }

    public String getIsSys() {
        return this.isSys;
    }

    public void setIsSys(String isSys) {
        this.isSys = isSys;
    }

    public String getUseable() {
        return this.useable;
    }

    public void setUseable(String useable) {
        this.useable = useable;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleDO (");

        sb.append(id);
        sb.append(", ").append(officeId);
        sb.append(", ").append(name);
        sb.append(", ").append(enname);
        sb.append(", ").append(roleType);
        sb.append(", ").append(dataScope);
        sb.append(", ").append(isSys);
        sb.append(", ").append(useable);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
