/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuDO implements Serializable {

    private static final long serialVersionUID = 635961655;

    private Long    id;
    private Integer menuId;
    private Integer roleId;

    public SysRoleMenuDO() {}

    public SysRoleMenuDO(SysRoleMenuDO value) {
        this.id = value.id;
        this.menuId = value.menuId;
        this.roleId = value.roleId;
    }

    public SysRoleMenuDO(
        Long    id,
        Integer menuId,
        Integer roleId
    ) {
        this.id = id;
        this.menuId = menuId;
        this.roleId = roleId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleMenuDO (");

        sb.append(id);
        sb.append(", ").append(menuId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
