/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;


/**
 * 角色-菜单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenuDO implements Serializable {

    private static final long serialVersionUID = -70814179;

    private String roleId;
    private String menuId;

    public SysRoleMenuDO() {}

    public SysRoleMenuDO(SysRoleMenuDO value) {
        this.roleId = value.roleId;
        this.menuId = value.menuId;
    }

    public SysRoleMenuDO(
        String roleId,
        String menuId
    ) {
        this.roleId = roleId;
        this.menuId = menuId;
    }

    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getMenuId() {
        return this.menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleMenuDO (");

        sb.append(roleId);
        sb.append(", ").append(menuId);

        sb.append(")");
        return sb.toString();
    }
}
