/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysSystemDO implements Serializable {

    private static final long serialVersionUID = 749662099;

    private Long      id;
    private String    name;
    private String    useable;
    private String    code;
    private Timestamp gmtCreate;
    private Timestamp gmtModified;
    private String    defFlag;

    public SysSystemDO() {}

    public SysSystemDO(SysSystemDO value) {
        this.id = value.id;
        this.name = value.name;
        this.useable = value.useable;
        this.code = value.code;
        this.gmtCreate = value.gmtCreate;
        this.gmtModified = value.gmtModified;
        this.defFlag = value.defFlag;
    }

    public SysSystemDO(
        Long      id,
        String    name,
        String    useable,
        String    code,
        Timestamp gmtCreate,
        Timestamp gmtModified,
        String    defFlag
    ) {
        this.id = id;
        this.name = name;
        this.useable = useable;
        this.code = code;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.defFlag = defFlag;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUseable() {
        return this.useable;
    }

    public void setUseable(String useable) {
        this.useable = useable;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Timestamp getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtCreate(Timestamp gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Timestamp getGmtModified() {
        return this.gmtModified;
    }

    public void setGmtModified(Timestamp gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getDefFlag() {
        return this.defFlag;
    }

    public void setDefFlag(String defFlag) {
        this.defFlag = defFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysSystemDO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(useable);
        sb.append(", ").append(code);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(defFlag);

        sb.append(")");
        return sb.toString();
    }
}
