/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserDO implements Serializable {

    private static final long serialVersionUID = -1811191315;

    private String    id;
    private String    companyId;
    private String    officeId;
    private String    loginName;
    private String    password;
    private String    no;
    private String    name;
    private String    email;
    private String    phone;
    private String    mobile;
    private String    userType;
    private String    photo;
    private String    loginIp;
    private Timestamp loginDate;
    private String    loginFlag;
    private String    createBy;
    private Timestamp createDate;
    private String    updateBy;
    private Timestamp updateDate;
    private String    remarks;
    private String    delFlag;

    public SysUserDO() {}

    public SysUserDO(SysUserDO value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.officeId = value.officeId;
        this.loginName = value.loginName;
        this.password = value.password;
        this.no = value.no;
        this.name = value.name;
        this.email = value.email;
        this.phone = value.phone;
        this.mobile = value.mobile;
        this.userType = value.userType;
        this.photo = value.photo;
        this.loginIp = value.loginIp;
        this.loginDate = value.loginDate;
        this.loginFlag = value.loginFlag;
        this.createBy = value.createBy;
        this.createDate = value.createDate;
        this.updateBy = value.updateBy;
        this.updateDate = value.updateDate;
        this.remarks = value.remarks;
        this.delFlag = value.delFlag;
    }

    public SysUserDO(
        String    id,
        String    companyId,
        String    officeId,
        String    loginName,
        String    password,
        String    no,
        String    name,
        String    email,
        String    phone,
        String    mobile,
        String    userType,
        String    photo,
        String    loginIp,
        Timestamp loginDate,
        String    loginFlag,
        String    createBy,
        Timestamp createDate,
        String    updateBy,
        Timestamp updateDate,
        String    remarks,
        String    delFlag
    ) {
        this.id = id;
        this.companyId = companyId;
        this.officeId = officeId;
        this.loginName = loginName;
        this.password = password;
        this.no = no;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.userType = userType;
        this.photo = photo;
        this.loginIp = loginIp;
        this.loginDate = loginDate;
        this.loginFlag = loginFlag;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.remarks = remarks;
        this.delFlag = delFlag;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getOfficeId() {
        return this.officeId;
    }

    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNo() {
        return this.no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public Timestamp getLoginDate() {
        return this.loginDate;
    }

    public void setLoginDate(Timestamp loginDate) {
        this.loginDate = loginDate;
    }

    public String getLoginFlag() {
        return this.loginFlag;
    }

    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserDO (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(officeId);
        sb.append(", ").append(loginName);
        sb.append(", ").append(password);
        sb.append(", ").append(no);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(mobile);
        sb.append(", ").append(userType);
        sb.append(", ").append(photo);
        sb.append(", ").append(loginIp);
        sb.append(", ").append(loginDate);
        sb.append(", ").append(loginFlag);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(remarks);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
