/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRoleDO implements Serializable {

    private static final long serialVersionUID = -400214960;

    private ULong   id;
    private Integer userId;
    private Integer roleId;

    public SysUserRoleDO() {}

    public SysUserRoleDO(SysUserRoleDO value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public SysUserRoleDO(
        ULong   id,
        Integer userId,
        Integer roleId
    ) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserRoleDO (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
