/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysAreaDO;
import com.yueya.system.dao.tables.records.SysAreaRecord;

import java.sql.Timestamp;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.types.ULong;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 区域表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysAreaDao extends BaseDao<SysAreaRecord, SysAreaDO, ULong> {

    /**
     * Create a new SysAreaDao without any configuration
     */
    public SysAreaDao() {
        super(com.yueya.system.dao.tables.SysArea.SYS_AREA, SysAreaDO.class);
    }

    /**
     * Create a new SysAreaDao with an attached configuration
     */
    @Autowired
    public SysAreaDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysArea.SYS_AREA, SysAreaDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(SysAreaDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysAreaDO> fetchById(ULong... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysAreaDO fetchOneById(ULong value) {
        return fetchOne(com.yueya.system.dao.tables.SysArea.SYS_AREA.ID, value);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<SysAreaDO> fetchByParentId(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>parent_ids IN (values)</code>
     */
    public List<SysAreaDO> fetchByParentIds(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.PARENT_IDS, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysAreaDO> fetchByName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.NAME, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<SysAreaDO> fetchBySort(Integer... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.SORT, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<SysAreaDO> fetchByCode(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.CODE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<SysAreaDO> fetchByType(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.TYPE, values);
    }

    /**
     * Fetch records that have <code>gmt_create IN (values)</code>
     */
    public List<SysAreaDO> fetchByGmtCreate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.GMT_CREATE, values);
    }

    /**
     * Fetch records that have <code>gmt_modified IN (values)</code>
     */
    public List<SysAreaDO> fetchByGmtModified(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.GMT_MODIFIED, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysAreaDO> fetchByRemarks(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysAreaDO> fetchByDelFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysArea.SYS_AREA.DEL_FLAG, values);
    }
}
