/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.SysUserRole;
import com.yueya.system.dao.tables.pojos.SysMenuDO;
import com.yueya.system.dao.tables.records.SysMenuRecord;

import java.sql.Timestamp;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysMenuDao extends BaseDao<SysMenuRecord, SysMenuDO, Long> {

    /**
     * Create a new SysMenuDao without any configuration
     */
    public SysMenuDao() {
        super(com.yueya.system.dao.tables.SysMenu.SYS_MENU, SysMenuDO.class);
    }

    /**
     * Create a new SysMenuDao with an attached configuration
     */
    @Autowired
    public SysMenuDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysMenu.SYS_MENU, SysMenuDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysMenuDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysMenuDO> fetchById(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysMenuDO fetchOneById(Long value) {
        return fetchOne(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysMenuDO> fetchByName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<SysMenuDO> fetchByParentId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>parent_ids IN (values)</code>
     */
    public List<SysMenuDO> fetchByParentIds(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PARENT_IDS, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<SysMenuDO> fetchByType(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.TYPE, values);
    }

    /**
     * Fetch records that have <code>tree_sort IN (values)</code>
     */
    public List<SysMenuDO> fetchByTreeSort(Integer... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.TREE_SORT, values);
    }

    /**
     * Fetch records that have <code>system_code IN (values)</code>
     */
    public List<SysMenuDO> fetchBySystemCode(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.SYSTEM_CODE, values);
    }

    /**
     * Fetch records that have <code>all_sort IN (values)</code>
     */
    public List<SysMenuDO> fetchByAllSort(Integer... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ALL_SORT, values);
    }

    /**
     * Fetch records that have <code>href IN (values)</code>
     */
    public List<SysMenuDO> fetchByHref(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.HREF, values);
    }

    /**
     * Fetch records that have <code>target IN (values)</code>
     */
    public List<SysMenuDO> fetchByTarget(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.TARGET, values);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<SysMenuDO> fetchByIcon(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ICON, values);
    }

    /**
     * Fetch records that have <code>color IN (values)</code>
     */
    public List<SysMenuDO> fetchByColor(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.COLOR, values);
    }

    /**
     * Fetch records that have <code>weight IN (values)</code>
     */
    public List<SysMenuDO> fetchByWeight(Short... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.WEIGHT, values);
    }

    /**
     * Fetch records that have <code>useable IN (values)</code>
     */
    public List<SysMenuDO> fetchByUseable(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.USEABLE, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysMenuDO> fetchByRemarks(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.REMARKS, values);
    }

    /**
     * Fetch records that have <code>gmt_create IN (values)</code>
     */
    public List<SysMenuDO> fetchByGmtCreate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.GMT_CREATE, values);
    }

    /**
     * Fetch records that have <code>gmt_modified IN (values)</code>
     */
    public List<SysMenuDO> fetchByGmtModified(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.GMT_MODIFIED, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysMenuDO> fetchByDelFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.DEL_FLAG, values);
    }
    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<SysMenuDO> fetchByPermission(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PERMISSION, values);
    }

    public List<SysMenuDO> fetchMenusByUserId(Long userId) {
        DSLContext create= DSL.using(super.configuration());
        List<SysMenuDO> list=create.select()
                .from(getTable())
                .innerJoin(SysRoleMenu.SYS_ROLE_MENU)
                .on(SysRoleMenu.SYS_ROLE_MENU.MENU_ID.eq(SysMenu.SYS_MENU.ID))
                .innerJoin(SysUserRole.SYS_USER_ROLE)
                .on(SysUserRole.SYS_USER_ROLE.ROLE_ID.eq(SysRoleMenu.SYS_ROLE_MENU.ROLE_ID))
                .where(SysUserRole.SYS_USER_ROLE.USER_ID.eq(userId)
                .and(SysMenu.SYS_MENU.USEABLE.eq(ENABLE))
                .and(SysMenu.SYS_MENU.DEL_FLAG.eq(DEL_NORMAL)))
                .fetchInto(getType());
        return list;
    }

    public List<SysMenuDO> fetchMenusByUserId(Long userId,String systemCode) {
        DSLContext create= DSL.using(super.configuration());
        List<SysMenuDO> list=create.select()
                .from(getTable())
                .innerJoin(SysRoleMenu.SYS_ROLE_MENU)
                .on(SysRoleMenu.SYS_ROLE_MENU.MENU_ID.eq(SysMenu.SYS_MENU.ID))
                .innerJoin(SysUserRole.SYS_USER_ROLE)
                .on(SysUserRole.SYS_USER_ROLE.ROLE_ID.eq(SysRoleMenu.SYS_ROLE_MENU.ROLE_ID))
                .where(SysUserRole.SYS_USER_ROLE.USER_ID.eq(userId)
                .and(SysMenu.SYS_MENU.USEABLE.eq(ENABLE))
                .and(SysMenu.SYS_MENU.DEL_FLAG.eq(DEL_NORMAL)))
                .and(SysMenu.SYS_MENU.SYSTEM_CODE.eq(systemCode))
                .fetchInto(getType());
        return list;
    }

}
