/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysMenuDO;
import com.yueya.system.dao.tables.records.SysMenuRecord;

import java.sql.Timestamp;
import java.util.List;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysMenuDao extends BaseDao<SysMenuRecord, SysMenuDO, String> {

    /**
     * Create a new SysMenuDao without any configuration
     */
    public SysMenuDao() {
        super(com.yueya.system.dao.tables.SysMenu.SYS_MENU, SysMenuDO.class);
    }

    /**
     * Create a new SysMenuDao with an attached configuration
     */
    @Autowired
    public SysMenuDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysMenu.SYS_MENU, SysMenuDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(SysMenuDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysMenuDO> fetchById(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysMenuDO fetchOneById(String value) {
        return fetchOne(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ID, value);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<SysMenuDO> fetchByParentId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>parent_ids IN (values)</code>
     */
    public List<SysMenuDO> fetchByParentIds(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PARENT_IDS, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysMenuDO> fetchByName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.NAME, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<SysMenuDO> fetchBySort(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.SORT, values);
    }

    /**
     * Fetch records that have <code>href IN (values)</code>
     */
    public List<SysMenuDO> fetchByHref(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.HREF, values);
    }

    /**
     * Fetch records that have <code>target IN (values)</code>
     */
    public List<SysMenuDO> fetchByTarget(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.TARGET, values);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<SysMenuDO> fetchByIcon(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.ICON, values);
    }

    /**
     * Fetch records that have <code>is_show IN (values)</code>
     */
    public List<SysMenuDO> fetchByIsShow(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.IS_SHOW, values);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<SysMenuDO> fetchByPermission(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.PERMISSION, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<SysMenuDO> fetchByCreateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<SysMenuDO> fetchByCreateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<SysMenuDO> fetchByUpdateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<SysMenuDO> fetchByUpdateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysMenuDO> fetchByRemarks(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysMenuDO> fetchByDelFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysMenu.SYS_MENU.DEL_FLAG, values);
    }
}
