/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.SysMenu;
import com.yueya.system.dao.tables.SysRoleMenu;
import com.yueya.system.dao.tables.pojos.SysMenuDO;
import com.yueya.system.dao.tables.pojos.SysRoleMenuDO;
import com.yueya.system.dao.tables.records.SysRoleMenuRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysRoleMenuDao extends BaseDao<SysRoleMenuRecord, SysRoleMenuDO, Long> {

    /**
     * Create a new SysRoleMenuDao without any configuration
     */
    public SysRoleMenuDao() {
        super(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuDO.class);
    }

    /**
     * Create a new SysRoleMenuDao with an attached configuration
     */
    @Autowired
    public SysRoleMenuDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(SysRoleMenuDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysRoleMenuDO> fetchById(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysRoleMenuDO fetchOneById(Long value) {
        return fetchOne(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.ID, value);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<SysRoleMenuDO> fetchByMenuId(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.MENU_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<SysRoleMenuDO> fetchByRoleId(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.ROLE_ID, values);
    }

    public List<SysRoleMenuDO> fetchMenuByRole(String roleId) {
        DSLContext create= DSL.using(super.configuration());
        List<SysRoleMenuDO> list=create.select(getFields())
                .from(getTable())
                .innerJoin(SysMenu.SYS_MENU)
                .on(SysRoleMenu.SYS_ROLE_MENU.MENU_ID.eq(SysMenu.SYS_MENU.ID))
                .where(SysRoleMenu.SYS_ROLE_MENU.ROLE_ID.eq(Long.valueOf(roleId))
                        .and(SysMenu.SYS_MENU.USEABLE.eq(ENABLE))
                        .and(SysMenu.SYS_MENU.DEL_FLAG.eq(DEL_NORMAL)))
                //.and(SysMenu.SYS_MENU.SYSTEM_CODE.eq(systemCode))
                .fetchInto(getType());
        return list;
    }
}
