/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysRoleMenuDO;
import com.yueya.system.dao.tables.records.SysRoleMenuRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 角色-菜单
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysRoleMenuDao extends BaseDao<SysRoleMenuRecord, SysRoleMenuDO, Record2<String, String>> {

    /**
     * Create a new SysRoleMenuDao without any configuration
     */
    public SysRoleMenuDao() {
        super(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuDO.class);
    }

    /**
     * Create a new SysRoleMenuDao with an attached configuration
     */
    @Autowired
    public SysRoleMenuDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU, SysRoleMenuDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(SysRoleMenuDO object) {
        return compositeKeyRecord(object.getRoleId(), object.getMenuId());
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<SysRoleMenuDO> fetchByRoleId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<SysRoleMenuDO> fetchByMenuId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleMenu.SYS_ROLE_MENU.MENU_ID, values);
    }
}
