/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysRoleDO;
import com.yueya.system.dao.tables.records.SysRoleRecord;

import java.sql.Timestamp;
import java.util.List;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysRoleDao extends BaseDao<SysRoleRecord, SysRoleDO, String> {

    /**
     * Create a new SysRoleDao without any configuration
     */
    public SysRoleDao() {
        super(com.yueya.system.dao.tables.SysRole.SYS_ROLE, SysRoleDO.class);
    }

    /**
     * Create a new SysRoleDao with an attached configuration
     */
    @Autowired
    public SysRoleDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysRole.SYS_ROLE, SysRoleDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(SysRoleDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysRoleDO> fetchById(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysRoleDO fetchOneById(String value) {
        return fetchOne(com.yueya.system.dao.tables.SysRole.SYS_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>office_id IN (values)</code>
     */
    public List<SysRoleDO> fetchByOfficeId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.OFFICE_ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysRoleDO> fetchByName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.NAME, values);
    }

    /**
     * Fetch records that have <code>enname IN (values)</code>
     */
    public List<SysRoleDO> fetchByEnname(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.ENNAME, values);
    }

    /**
     * Fetch records that have <code>role_type IN (values)</code>
     */
    public List<SysRoleDO> fetchByRoleType(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.ROLE_TYPE, values);
    }

    /**
     * Fetch records that have <code>data_scope IN (values)</code>
     */
    public List<SysRoleDO> fetchByDataScope(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.DATA_SCOPE, values);
    }

    /**
     * Fetch records that have <code>is_sys IN (values)</code>
     */
    public List<SysRoleDO> fetchByIsSys(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.IS_SYS, values);
    }

    /**
     * Fetch records that have <code>useable IN (values)</code>
     */
    public List<SysRoleDO> fetchByUseable(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.USEABLE, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<SysRoleDO> fetchByCreateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<SysRoleDO> fetchByCreateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<SysRoleDO> fetchByUpdateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<SysRoleDO> fetchByUpdateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysRoleDO> fetchByRemarks(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysRoleDO> fetchByDelFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRole.SYS_ROLE.DEL_FLAG, values);
    }
}
