/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysRoleOrgDO;
import com.yueya.system.dao.tables.records.SysRoleOrgRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysRoleOrgDao extends BaseDao<SysRoleOrgRecord, SysRoleOrgDO, Record2<Long, Long>> {

    /**
     * Create a new SysRoleOrgDao without any configuration
     */
    public SysRoleOrgDao() {
        super(com.yueya.system.dao.tables.SysRoleOrg.SYS_ROLE_ORG, SysRoleOrgDO.class);
    }

    /**
     * Create a new SysRoleOrgDao with an attached configuration
     */
    @Autowired
    public SysRoleOrgDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysRoleOrg.SYS_ROLE_ORG, SysRoleOrgDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(SysRoleOrgDO object) {
        return compositeKeyRecord(object.getRoleId(), object.getOrgId());
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<SysRoleOrgDO> fetchByRoleId(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleOrg.SYS_ROLE_ORG.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>org_id IN (values)</code>
     */
    public List<SysRoleOrgDO> fetchByOrgId(Long... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleOrg.SYS_ROLE_ORG.ORG_ID, values);
    }
}
