/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysRoleOfficeDO;
import com.yueya.system.dao.tables.records.SysRoleOfficeRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 角色-机构
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysRoleOfficeDao extends BaseDao<SysRoleOfficeRecord, SysRoleOfficeDO, Record2<String, String>> {

    /**
     * Create a new SysRoleOfficeDao without any configuration
     */
    public SysRoleOfficeDao() {
        super(com.yueya.system.dao.tables.SysRoleOffice.SYS_ROLE_OFFICE, SysRoleOfficeDO.class);
    }

    /**
     * Create a new SysRoleOfficeDao with an attached configuration
     */
    @Autowired
    public SysRoleOfficeDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysRoleOffice.SYS_ROLE_OFFICE, SysRoleOfficeDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(SysRoleOfficeDO object) {
        return compositeKeyRecord(object.getRoleId(), object.getOfficeId());
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<SysRoleOfficeDO> fetchByRoleId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleOffice.SYS_ROLE_OFFICE.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>office_id IN (values)</code>
     */
    public List<SysRoleOfficeDO> fetchByOfficeId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysRoleOffice.SYS_ROLE_OFFICE.OFFICE_ID, values);
    }
}
