/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.daos;


import com.yueya.common.base.BaseDao;
import com.yueya.system.dao.tables.pojos.SysUserDO;
import com.yueya.system.dao.tables.records.SysUserRecord;

import java.sql.Timestamp;
import java.util.List;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUserDao extends BaseDao<SysUserRecord, SysUserDO, String> {

    /**
     * Create a new SysUserDao without any configuration
     */
    public SysUserDao() {
        super(com.yueya.system.dao.tables.SysUser.SYS_USER, SysUserDO.class);
    }

    /**
     * Create a new SysUserDao with an attached configuration
     */
    @Autowired
    public SysUserDao(Configuration configuration) {
        super(com.yueya.system.dao.tables.SysUser.SYS_USER, SysUserDO.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(SysUserDO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<SysUserDO> fetchById(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public SysUserDO fetchOneById(String value) {
        return fetchOne(com.yueya.system.dao.tables.SysUser.SYS_USER.ID, value);
    }

    /**
     * Fetch records that have <code>company_id IN (values)</code>
     */
    public List<SysUserDO> fetchByCompanyId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>office_id IN (values)</code>
     */
    public List<SysUserDO> fetchByOfficeId(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.OFFICE_ID, values);
    }

    /**
     * Fetch records that have <code>login_name IN (values)</code>
     */
    public List<SysUserDO> fetchByLoginName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.LOGIN_NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<SysUserDO> fetchByPassword(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>no IN (values)</code>
     */
    public List<SysUserDO> fetchByNo(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.NO, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<SysUserDO> fetchByName(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.NAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<SysUserDO> fetchByEmail(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<SysUserDO> fetchByPhone(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>mobile IN (values)</code>
     */
    public List<SysUserDO> fetchByMobile(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.MOBILE, values);
    }

    /**
     * Fetch records that have <code>user_type IN (values)</code>
     */
    public List<SysUserDO> fetchByUserType(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.USER_TYPE, values);
    }

    /**
     * Fetch records that have <code>photo IN (values)</code>
     */
    public List<SysUserDO> fetchByPhoto(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.PHOTO, values);
    }

    /**
     * Fetch records that have <code>login_ip IN (values)</code>
     */
    public List<SysUserDO> fetchByLoginIp(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.LOGIN_IP, values);
    }

    /**
     * Fetch records that have <code>login_date IN (values)</code>
     */
    public List<SysUserDO> fetchByLoginDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.LOGIN_DATE, values);
    }

    /**
     * Fetch records that have <code>login_flag IN (values)</code>
     */
    public List<SysUserDO> fetchByLoginFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.LOGIN_FLAG, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<SysUserDO> fetchByCreateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<SysUserDO> fetchByCreateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<SysUserDO> fetchByUpdateBy(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<SysUserDO> fetchByUpdateDate(Timestamp... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<SysUserDO> fetchByRemarks(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.REMARKS, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<SysUserDO> fetchByDelFlag(String... values) {
        return fetch(com.yueya.system.dao.tables.SysUser.SYS_USER.DEL_FLAG, values);
    }
}
