/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables;


import com.yueya.system.dao.Indexes;
import com.yueya.system.dao.Jeesite;
import com.yueya.system.dao.Keys;
import com.yueya.system.dao.tables.records.SysMenuRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu extends TableImpl<SysMenuRecord> {

    private static final long serialVersionUID = -1585076951;

    /**
     * The reference instance of <code>jeesite.sys_menu</code>
     */
    public static final SysMenu SYS_MENU = new SysMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysMenuRecord> getRecordType() {
        return SysMenuRecord.class;
    }

    /**
     * The column <code>jeesite.sys_menu.id</code>. 编号
     */
    public final TableField<SysMenuRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "编号");

    /**
     * The column <code>jeesite.sys_menu.parent_id</code>. 父级编号
     */
    public final TableField<SysMenuRecord, String> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "父级编号");

    /**
     * The column <code>jeesite.sys_menu.parent_ids</code>. 所有父级编号
     */
    public final TableField<SysMenuRecord, String> PARENT_IDS = createField("parent_ids", org.jooq.impl.SQLDataType.VARCHAR(2000).nullable(false), this, "所有父级编号");

    /**
     * The column <code>jeesite.sys_menu.name</code>. 名称
     */
    public final TableField<SysMenuRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "名称");

    /**
     * The column <code>jeesite.sys_menu.sort</code>. 排序
     */
    public final TableField<SysMenuRecord, Long> SORT = createField("sort", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "排序");

    /**
     * The column <code>jeesite.sys_menu.href</code>. 链接
     */
    public final TableField<SysMenuRecord, String> HREF = createField("href", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "链接");

    /**
     * The column <code>jeesite.sys_menu.target</code>. 目标
     */
    public final TableField<SysMenuRecord, String> TARGET = createField("target", org.jooq.impl.SQLDataType.VARCHAR(20), this, "目标");

    /**
     * The column <code>jeesite.sys_menu.icon</code>. 图标
     */
    public final TableField<SysMenuRecord, String> ICON = createField("icon", org.jooq.impl.SQLDataType.VARCHAR(100), this, "图标");

    /**
     * The column <code>jeesite.sys_menu.is_show</code>. 是否在菜单中显示
     */
    public final TableField<SysMenuRecord, String> IS_SHOW = createField("is_show", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "是否在菜单中显示");

    /**
     * The column <code>jeesite.sys_menu.permission</code>. 权限标识
     */
    public final TableField<SysMenuRecord, String> PERMISSION = createField("permission", org.jooq.impl.SQLDataType.VARCHAR(200), this, "权限标识");

    /**
     * The column <code>jeesite.sys_menu.create_by</code>. 创建者
     */
    public final TableField<SysMenuRecord, String> CREATE_BY = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "创建者");

    /**
     * The column <code>jeesite.sys_menu.create_date</code>. 创建时间
     */
    public final TableField<SysMenuRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>jeesite.sys_menu.update_by</code>. 更新者
     */
    public final TableField<SysMenuRecord, String> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "更新者");

    /**
     * The column <code>jeesite.sys_menu.update_date</code>. 更新时间
     */
    public final TableField<SysMenuRecord, Timestamp> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "更新时间");

    /**
     * The column <code>jeesite.sys_menu.remarks</code>. 备注信息
     */
    public final TableField<SysMenuRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注信息");

    /**
     * The column <code>jeesite.sys_menu.del_flag</code>. 删除标记
     */
    public final TableField<SysMenuRecord, String> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.CHAR)), this, "删除标记");

    /**
     * Create a <code>jeesite.sys_menu</code> table reference
     */
    public SysMenu() {
        this(DSL.name("sys_menu"), null);
    }

    /**
     * Create an aliased <code>jeesite.sys_menu</code> table reference
     */
    public SysMenu(String alias) {
        this(DSL.name(alias), SYS_MENU);
    }

    /**
     * Create an aliased <code>jeesite.sys_menu</code> table reference
     */
    public SysMenu(Name alias) {
        this(alias, SYS_MENU);
    }

    private SysMenu(Name alias, Table<SysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysMenu(Name alias, Table<SysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("菜单表"));
    }

    public <O extends Record> SysMenu(Table<O> child, ForeignKey<O, SysMenuRecord> key) {
        super(child, key, SYS_MENU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jeesite.JEESITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_MENU_PRIMARY, Indexes.SYS_MENU_SYS_MENU_DEL_FLAG, Indexes.SYS_MENU_SYS_MENU_PARENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysMenuRecord> getPrimaryKey() {
        return Keys.KEY_SYS_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<SysMenuRecord>>asList(Keys.KEY_SYS_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenu as(String alias) {
        return new SysMenu(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenu as(Name alias) {
        return new SysMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysMenu rename(String name) {
        return new SysMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysMenu rename(Name name) {
        return new SysMenu(name, null);
    }
}
