/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables;


import com.yueya.system.dao.Indexes;
import com.yueya.system.dao.Jeesite;
import com.yueya.system.dao.Keys;
import com.yueya.system.dao.tables.records.SysOfficeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 机构表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOffice extends TableImpl<SysOfficeRecord> {

    private static final long serialVersionUID = 1747979305;

    /**
     * The reference instance of <code>jeesite.sys_office</code>
     */
    public static final SysOffice SYS_OFFICE = new SysOffice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysOfficeRecord> getRecordType() {
        return SysOfficeRecord.class;
    }

    /**
     * The column <code>jeesite.sys_office.id</code>. 编号
     */
    public final TableField<SysOfficeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "编号");

    /**
     * The column <code>jeesite.sys_office.parent_id</code>. 父级编号
     */
    public final TableField<SysOfficeRecord, String> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "父级编号");

    /**
     * The column <code>jeesite.sys_office.parent_ids</code>. 所有父级编号
     */
    public final TableField<SysOfficeRecord, String> PARENT_IDS = createField("parent_ids", org.jooq.impl.SQLDataType.VARCHAR(2000).nullable(false), this, "所有父级编号");

    /**
     * The column <code>jeesite.sys_office.name</code>. 名称
     */
    public final TableField<SysOfficeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "名称");

    /**
     * The column <code>jeesite.sys_office.sort</code>. 排序
     */
    public final TableField<SysOfficeRecord, Long> SORT = createField("sort", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "排序");

    /**
     * The column <code>jeesite.sys_office.area_id</code>. 归属区域
     */
    public final TableField<SysOfficeRecord, String> AREA_ID = createField("area_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "归属区域");

    /**
     * The column <code>jeesite.sys_office.code</code>. 区域编码
     */
    public final TableField<SysOfficeRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(100), this, "区域编码");

    /**
     * The column <code>jeesite.sys_office.type</code>. 机构类型
     */
    public final TableField<SysOfficeRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "机构类型");

    /**
     * The column <code>jeesite.sys_office.grade</code>. 机构等级
     */
    public final TableField<SysOfficeRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "机构等级");

    /**
     * The column <code>jeesite.sys_office.address</code>. 联系地址
     */
    public final TableField<SysOfficeRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "联系地址");

    /**
     * The column <code>jeesite.sys_office.zip_code</code>. 邮政编码
     */
    public final TableField<SysOfficeRecord, String> ZIP_CODE = createField("zip_code", org.jooq.impl.SQLDataType.VARCHAR(100), this, "邮政编码");

    /**
     * The column <code>jeesite.sys_office.master</code>. 负责人
     */
    public final TableField<SysOfficeRecord, String> MASTER = createField("master", org.jooq.impl.SQLDataType.VARCHAR(100), this, "负责人");

    /**
     * The column <code>jeesite.sys_office.phone</code>. 电话
     */
    public final TableField<SysOfficeRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(200), this, "电话");

    /**
     * The column <code>jeesite.sys_office.fax</code>. 传真
     */
    public final TableField<SysOfficeRecord, String> FAX = createField("fax", org.jooq.impl.SQLDataType.VARCHAR(200), this, "传真");

    /**
     * The column <code>jeesite.sys_office.email</code>. 邮箱
     */
    public final TableField<SysOfficeRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(200), this, "邮箱");

    /**
     * The column <code>jeesite.sys_office.USEABLE</code>. 是否启用
     */
    public final TableField<SysOfficeRecord, String> USEABLE = createField("USEABLE", org.jooq.impl.SQLDataType.VARCHAR(64), this, "是否启用");

    /**
     * The column <code>jeesite.sys_office.PRIMARY_PERSON</code>. 主负责人
     */
    public final TableField<SysOfficeRecord, String> PRIMARY_PERSON = createField("PRIMARY_PERSON", org.jooq.impl.SQLDataType.VARCHAR(64), this, "主负责人");

    /**
     * The column <code>jeesite.sys_office.DEPUTY_PERSON</code>. 副负责人
     */
    public final TableField<SysOfficeRecord, String> DEPUTY_PERSON = createField("DEPUTY_PERSON", org.jooq.impl.SQLDataType.VARCHAR(64), this, "副负责人");

    /**
     * The column <code>jeesite.sys_office.create_by</code>. 创建者
     */
    public final TableField<SysOfficeRecord, String> CREATE_BY = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "创建者");

    /**
     * The column <code>jeesite.sys_office.create_date</code>. 创建时间
     */
    public final TableField<SysOfficeRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>jeesite.sys_office.update_by</code>. 更新者
     */
    public final TableField<SysOfficeRecord, String> UPDATE_BY = createField("update_by", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "更新者");

    /**
     * The column <code>jeesite.sys_office.update_date</code>. 更新时间
     */
    public final TableField<SysOfficeRecord, Timestamp> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "更新时间");

    /**
     * The column <code>jeesite.sys_office.remarks</code>. 备注信息
     */
    public final TableField<SysOfficeRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注信息");

    /**
     * The column <code>jeesite.sys_office.del_flag</code>. 删除标记
     */
    public final TableField<SysOfficeRecord, String> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.CHAR)), this, "删除标记");

    /**
     * Create a <code>jeesite.sys_office</code> table reference
     */
    public SysOffice() {
        this(DSL.name("sys_office"), null);
    }

    /**
     * Create an aliased <code>jeesite.sys_office</code> table reference
     */
    public SysOffice(String alias) {
        this(DSL.name(alias), SYS_OFFICE);
    }

    /**
     * Create an aliased <code>jeesite.sys_office</code> table reference
     */
    public SysOffice(Name alias) {
        this(alias, SYS_OFFICE);
    }

    private SysOffice(Name alias, Table<SysOfficeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysOffice(Name alias, Table<SysOfficeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("机构表"));
    }

    public <O extends Record> SysOffice(Table<O> child, ForeignKey<O, SysOfficeRecord> key) {
        super(child, key, SYS_OFFICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jeesite.JEESITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_OFFICE_PRIMARY, Indexes.SYS_OFFICE_SYS_OFFICE_DEL_FLAG, Indexes.SYS_OFFICE_SYS_OFFICE_PARENT_ID, Indexes.SYS_OFFICE_SYS_OFFICE_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysOfficeRecord> getPrimaryKey() {
        return Keys.KEY_SYS_OFFICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysOfficeRecord>> getKeys() {
        return Arrays.<UniqueKey<SysOfficeRecord>>asList(Keys.KEY_SYS_OFFICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOffice as(String alias) {
        return new SysOffice(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOffice as(Name alias) {
        return new SysOffice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysOffice rename(String name) {
        return new SysOffice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysOffice rename(Name name) {
        return new SysOffice(name, null);
    }
}
