/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables;


import com.yueya.system.dao.Indexes;
import com.yueya.system.dao.Jeesite;
import com.yueya.system.dao.Keys;
import com.yueya.system.dao.tables.records.SysRoleOfficeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 角色-机构
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleOffice extends TableImpl<SysRoleOfficeRecord> {

    private static final long serialVersionUID = 1820745947;

    /**
     * The reference instance of <code>jeesite.sys_role_office</code>
     */
    public static final SysRoleOffice SYS_ROLE_OFFICE = new SysRoleOffice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysRoleOfficeRecord> getRecordType() {
        return SysRoleOfficeRecord.class;
    }

    /**
     * The column <code>jeesite.sys_role_office.role_id</code>. 角色编号
     */
    public final TableField<SysRoleOfficeRecord, String> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "角色编号");

    /**
     * The column <code>jeesite.sys_role_office.office_id</code>. 机构编号
     */
    public final TableField<SysRoleOfficeRecord, String> OFFICE_ID = createField("office_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "机构编号");

    /**
     * Create a <code>jeesite.sys_role_office</code> table reference
     */
    public SysRoleOffice() {
        this(DSL.name("sys_role_office"), null);
    }

    /**
     * Create an aliased <code>jeesite.sys_role_office</code> table reference
     */
    public SysRoleOffice(String alias) {
        this(DSL.name(alias), SYS_ROLE_OFFICE);
    }

    /**
     * Create an aliased <code>jeesite.sys_role_office</code> table reference
     */
    public SysRoleOffice(Name alias) {
        this(alias, SYS_ROLE_OFFICE);
    }

    private SysRoleOffice(Name alias, Table<SysRoleOfficeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysRoleOffice(Name alias, Table<SysRoleOfficeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("角色-机构"));
    }

    public <O extends Record> SysRoleOffice(Table<O> child, ForeignKey<O, SysRoleOfficeRecord> key) {
        super(child, key, SYS_ROLE_OFFICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Jeesite.JEESITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_ROLE_OFFICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysRoleOfficeRecord> getPrimaryKey() {
        return Keys.KEY_SYS_ROLE_OFFICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysRoleOfficeRecord>> getKeys() {
        return Arrays.<UniqueKey<SysRoleOfficeRecord>>asList(Keys.KEY_SYS_ROLE_OFFICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOffice as(String alias) {
        return new SysRoleOffice(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOffice as(Name alias) {
        return new SysRoleOffice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysRoleOffice rename(String name) {
        return new SysRoleOffice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysRoleOffice rename(Name name) {
        return new SysRoleOffice(name, null);
    }
}
