/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables;


import com.yueya.system.dao.Indexes;
import com.yueya.system.dao.Keys;
import com.yueya.system.dao.Pms;
import com.yueya.system.dao.tables.records.SysSystemRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysSystem extends TableImpl<SysSystemRecord> {

    private static final long serialVersionUID = -265158394;

    /**
     * The reference instance of <code>pms.sys_system</code>
     */
    public static final SysSystem SYS_SYSTEM = new SysSystem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysSystemRecord> getRecordType() {
        return SysSystemRecord.class;
    }

    /**
     * The column <code>pms.sys_system.id</code>.
     */
    public final TableField<SysSystemRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>pms.sys_system.name</code>. 系统名称
     */
    public final TableField<SysSystemRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "系统名称");

    /**
     * The column <code>pms.sys_system.useable</code>. 时候启用
     */
    public final TableField<SysSystemRecord, String> USEABLE = createField("useable", org.jooq.impl.SQLDataType.CHAR(1), this, "时候启用");

    /**
     * The column <code>pms.sys_system.code</code>. 系统标识码
     */
    public final TableField<SysSystemRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(64), this, "系统标识码");

    /**
     * The column <code>pms.sys_system.gmt_create</code>. 创建时间
     */
    public final TableField<SysSystemRecord, Timestamp> GMT_CREATE = createField("gmt_create", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>pms.sys_system.gmt_modified</code>. 修改时间
     */
    public final TableField<SysSystemRecord, Timestamp> GMT_MODIFIED = createField("gmt_modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "修改时间");

    /**
     * The column <code>pms.sys_system.def_flag</code>. 删除标记
     */
    public final TableField<SysSystemRecord, String> DEF_FLAG = createField("def_flag", org.jooq.impl.SQLDataType.VARCHAR(45), this, "删除标记");

    /**
     * Create a <code>pms.sys_system</code> table reference
     */
    public SysSystem() {
        this(DSL.name("sys_system"), null);
    }

    /**
     * Create an aliased <code>pms.sys_system</code> table reference
     */
    public SysSystem(String alias) {
        this(DSL.name(alias), SYS_SYSTEM);
    }

    /**
     * Create an aliased <code>pms.sys_system</code> table reference
     */
    public SysSystem(Name alias) {
        this(alias, SYS_SYSTEM);
    }

    private SysSystem(Name alias, Table<SysSystemRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysSystem(Name alias, Table<SysSystemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SysSystem(Table<O> child, ForeignKey<O, SysSystemRecord> key) {
        super(child, key, SYS_SYSTEM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pms.PMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_SYSTEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SysSystemRecord, ULong> getIdentity() {
        return Keys.IDENTITY_SYS_SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysSystemRecord> getPrimaryKey() {
        return Keys.KEY_SYS_SYSTEM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysSystemRecord>> getKeys() {
        return Arrays.<UniqueKey<SysSystemRecord>>asList(Keys.KEY_SYS_SYSTEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystem as(String alias) {
        return new SysSystem(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystem as(Name alias) {
        return new SysSystem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysSystem rename(String name) {
        return new SysSystem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysSystem rename(Name name) {
        return new SysSystem(name, null);
    }
}
