/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysArea;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 区域表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysAreaRecord extends UpdatableRecordImpl<SysAreaRecord> implements Record13<String, String, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, String> {

    private static final long serialVersionUID = 197038631;

    /**
     * Setter for <code>jeesite.sys_area.id</code>. 编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.id</code>. 编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_area.parent_id</code>. 父级编号
     */
    public void setParentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.parent_id</code>. 父级编号
     */
    public String getParentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jeesite.sys_area.parent_ids</code>. 所有父级编号
     */
    public void setParentIds(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.parent_ids</code>. 所有父级编号
     */
    public String getParentIds() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jeesite.sys_area.name</code>. 名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.name</code>. 名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jeesite.sys_area.sort</code>. 排序
     */
    public void setSort(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.sort</code>. 排序
     */
    public Long getSort() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>jeesite.sys_area.code</code>. 区域编码
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.code</code>. 区域编码
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jeesite.sys_area.type</code>. 区域类型
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.type</code>. 区域类型
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jeesite.sys_area.create_by</code>. 创建者
     */
    public void setCreateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.create_by</code>. 创建者
     */
    public String getCreateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jeesite.sys_area.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>jeesite.sys_area.update_by</code>. 更新者
     */
    public void setUpdateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.update_by</code>. 更新者
     */
    public String getUpdateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jeesite.sys_area.update_date</code>. 更新时间
     */
    public void setUpdateDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>jeesite.sys_area.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jeesite.sys_area.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jeesite.sys_area.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, Long, String, String, String, Timestamp, String, Timestamp, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysArea.SYS_AREA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysArea.SYS_AREA.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysArea.SYS_AREA.PARENT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysArea.SYS_AREA.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SysArea.SYS_AREA.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysArea.SYS_AREA.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysArea.SYS_AREA.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysArea.SYS_AREA.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysArea.SYS_AREA.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysArea.SYS_AREA.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return SysArea.SYS_AREA.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysArea.SYS_AREA.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SysArea.SYS_AREA.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value2(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value3(String value) {
        setParentIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value5(Long value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value6(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value8(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value9(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value10(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value11(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value12(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord value13(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysAreaRecord values(String value1, String value2, String value3, String value4, Long value5, String value6, String value7, String value8, Timestamp value9, String value10, Timestamp value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysAreaRecord
     */
    public SysAreaRecord() {
        super(SysArea.SYS_AREA);
    }

    /**
     * Create a detached, initialised SysAreaRecord
     */
    public SysAreaRecord(String id, String parentId, String parentIds, String name, Long sort, String code, String type, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate, String remarks, String delFlag) {
        super(SysArea.SYS_AREA);

        set(0, id);
        set(1, parentId);
        set(2, parentIds);
        set(3, name);
        set(4, sort);
        set(5, code);
        set(6, type);
        set(7, createBy);
        set(8, createDate);
        set(9, updateBy);
        set(10, updateDate);
        set(11, remarks);
        set(12, delFlag);
    }
}
