/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysDict;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictRecord extends UpdatableRecordImpl<SysDictRecord> implements Record13<String, String, String, String, String, Long, String, String, Timestamp, String, Timestamp, String, String> {

    private static final long serialVersionUID = -1522980131;

    /**
     * Setter for <code>jeesite.sys_dict.id</code>. 编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.id</code>. 编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_dict.value</code>. 数据值
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.value</code>. 数据值
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jeesite.sys_dict.label</code>. 标签名
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.label</code>. 标签名
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jeesite.sys_dict.type</code>. 类型
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.type</code>. 类型
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jeesite.sys_dict.description</code>. 描述
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jeesite.sys_dict.sort</code>. 排序（升序）
     */
    public void setSort(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.sort</code>. 排序（升序）
     */
    public Long getSort() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>jeesite.sys_dict.parent_id</code>. 父级编号
     */
    public void setParentId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.parent_id</code>. 父级编号
     */
    public String getParentId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jeesite.sys_dict.create_by</code>. 创建者
     */
    public void setCreateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.create_by</code>. 创建者
     */
    public String getCreateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jeesite.sys_dict.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>jeesite.sys_dict.update_by</code>. 更新者
     */
    public void setUpdateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.update_by</code>. 更新者
     */
    public String getUpdateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jeesite.sys_dict.update_date</code>. 更新时间
     */
    public void setUpdateDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>jeesite.sys_dict.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jeesite.sys_dict.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jeesite.sys_dict.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, Long, String, String, Timestamp, String, Timestamp, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, Long, String, String, Timestamp, String, Timestamp, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysDict.SYS_DICT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysDict.SYS_DICT.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysDict.SYS_DICT.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysDict.SYS_DICT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysDict.SYS_DICT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return SysDict.SYS_DICT.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysDict.SYS_DICT.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysDict.SYS_DICT.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysDict.SYS_DICT.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysDict.SYS_DICT.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return SysDict.SYS_DICT.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysDict.SYS_DICT.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SysDict.SYS_DICT.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value3(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value6(Long value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value7(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value8(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value9(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value10(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value11(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value12(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value13(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord values(String value1, String value2, String value3, String value4, String value5, Long value6, String value7, String value8, Timestamp value9, String value10, Timestamp value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysDictRecord
     */
    public SysDictRecord() {
        super(SysDict.SYS_DICT);
    }

    /**
     * Create a detached, initialised SysDictRecord
     */
    public SysDictRecord(String id, String value, String label, String type, String description, Long sort, String parentId, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate, String remarks, String delFlag) {
        super(SysDict.SYS_DICT);

        set(0, id);
        set(1, value);
        set(2, label);
        set(3, type);
        set(4, description);
        set(5, sort);
        set(6, parentId);
        set(7, createBy);
        set(8, createDate);
        set(9, updateBy);
        set(10, updateDate);
        set(11, remarks);
        set(12, delFlag);
    }
}
