/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysMenu;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends UpdatableRecordImpl<SysMenuRecord> implements Record16<String, String, String, String, Long, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> {

    private static final long serialVersionUID = 923052632;

    /**
     * Setter for <code>jeesite.sys_menu.id</code>. 编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.id</code>. 编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_menu.parent_id</code>. 父级编号
     */
    public void setParentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.parent_id</code>. 父级编号
     */
    public String getParentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jeesite.sys_menu.parent_ids</code>. 所有父级编号
     */
    public void setParentIds(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.parent_ids</code>. 所有父级编号
     */
    public String getParentIds() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jeesite.sys_menu.name</code>. 名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.name</code>. 名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jeesite.sys_menu.sort</code>. 排序
     */
    public void setSort(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.sort</code>. 排序
     */
    public Long getSort() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>jeesite.sys_menu.href</code>. 链接
     */
    public void setHref(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.href</code>. 链接
     */
    public String getHref() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jeesite.sys_menu.target</code>. 目标
     */
    public void setTarget(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.target</code>. 目标
     */
    public String getTarget() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jeesite.sys_menu.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jeesite.sys_menu.is_show</code>. 是否在菜单中显示
     */
    public void setIsShow(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.is_show</code>. 是否在菜单中显示
     */
    public String getIsShow() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jeesite.sys_menu.permission</code>. 权限标识
     */
    public void setPermission(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.permission</code>. 权限标识
     */
    public String getPermission() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jeesite.sys_menu.create_by</code>. 创建者
     */
    public void setCreateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.create_by</code>. 创建者
     */
    public String getCreateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jeesite.sys_menu.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>jeesite.sys_menu.update_by</code>. 更新者
     */
    public void setUpdateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.update_by</code>. 更新者
     */
    public String getUpdateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jeesite.sys_menu.update_date</code>. 更新时间
     */
    public void setUpdateDate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>jeesite.sys_menu.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(14);
    }

    /**
     * Setter for <code>jeesite.sys_menu.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>jeesite.sys_menu.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, Long, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<String, String, String, String, Long, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysMenu.SYS_MENU.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysMenu.SYS_MENU.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysMenu.SYS_MENU.PARENT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysMenu.SYS_MENU.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SysMenu.SYS_MENU.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysMenu.SYS_MENU.HREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysMenu.SYS_MENU.TARGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysMenu.SYS_MENU.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysMenu.SYS_MENU.IS_SHOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysMenu.SYS_MENU.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysMenu.SYS_MENU.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return SysMenu.SYS_MENU.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SysMenu.SYS_MENU.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return SysMenu.SYS_MENU.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return SysMenu.SYS_MENU.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return SysMenu.SYS_MENU.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getHref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIsShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getHref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIsShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value2(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value3(String value) {
        setParentIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value5(Long value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value6(String value) {
        setHref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value7(String value) {
        setTarget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value8(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value9(String value) {
        setIsShow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value10(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value11(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value12(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value13(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value14(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value15(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value16(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord values(String value1, String value2, String value3, String value4, Long value5, String value6, String value7, String value8, String value9, String value10, String value11, Timestamp value12, String value13, Timestamp value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(String id, String parentId, String parentIds, String name, Long sort, String href, String target, String icon, String isShow, String permission, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate, String remarks, String delFlag) {
        super(SysMenu.SYS_MENU);

        set(0, id);
        set(1, parentId);
        set(2, parentIds);
        set(3, name);
        set(4, sort);
        set(5, href);
        set(6, target);
        set(7, icon);
        set(8, isShow);
        set(9, permission);
        set(10, createBy);
        set(11, createDate);
        set(12, updateBy);
        set(13, updateDate);
        set(14, remarks);
        set(15, delFlag);
    }
}
