/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysOffice;

import java.sql.Timestamp;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 机构表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOfficeRecord extends UpdatableRecordImpl<SysOfficeRecord> {

    private static final long serialVersionUID = 1087606922;

    /**
     * Setter for <code>jeesite.sys_office.id</code>. 编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.id</code>. 编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_office.parent_id</code>. 父级编号
     */
    public void setParentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.parent_id</code>. 父级编号
     */
    public String getParentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jeesite.sys_office.parent_ids</code>. 所有父级编号
     */
    public void setParentIds(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.parent_ids</code>. 所有父级编号
     */
    public String getParentIds() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jeesite.sys_office.name</code>. 名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.name</code>. 名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jeesite.sys_office.sort</code>. 排序
     */
    public void setSort(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.sort</code>. 排序
     */
    public Long getSort() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>jeesite.sys_office.area_id</code>. 归属区域
     */
    public void setAreaId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.area_id</code>. 归属区域
     */
    public String getAreaId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jeesite.sys_office.code</code>. 区域编码
     */
    public void setCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.code</code>. 区域编码
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jeesite.sys_office.type</code>. 机构类型
     */
    public void setType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.type</code>. 机构类型
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jeesite.sys_office.grade</code>. 机构等级
     */
    public void setGrade(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.grade</code>. 机构等级
     */
    public String getGrade() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jeesite.sys_office.address</code>. 联系地址
     */
    public void setAddress(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.address</code>. 联系地址
     */
    public String getAddress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jeesite.sys_office.zip_code</code>. 邮政编码
     */
    public void setZipCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.zip_code</code>. 邮政编码
     */
    public String getZipCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jeesite.sys_office.master</code>. 负责人
     */
    public void setMaster(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.master</code>. 负责人
     */
    public String getMaster() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jeesite.sys_office.phone</code>. 电话
     */
    public void setPhone(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.phone</code>. 电话
     */
    public String getPhone() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jeesite.sys_office.fax</code>. 传真
     */
    public void setFax(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.fax</code>. 传真
     */
    public String getFax() {
        return (String) get(13);
    }

    /**
     * Setter for <code>jeesite.sys_office.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(14);
    }

    /**
     * Setter for <code>jeesite.sys_office.USEABLE</code>. 是否启用
     */
    public void setUseable(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.USEABLE</code>. 是否启用
     */
    public String getUseable() {
        return (String) get(15);
    }

    /**
     * Setter for <code>jeesite.sys_office.PRIMARY_PERSON</code>. 主负责人
     */
    public void setPrimaryPerson(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.PRIMARY_PERSON</code>. 主负责人
     */
    public String getPrimaryPerson() {
        return (String) get(16);
    }

    /**
     * Setter for <code>jeesite.sys_office.DEPUTY_PERSON</code>. 副负责人
     */
    public void setDeputyPerson(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.DEPUTY_PERSON</code>. 副负责人
     */
    public String getDeputyPerson() {
        return (String) get(17);
    }

    /**
     * Setter for <code>jeesite.sys_office.create_by</code>. 创建者
     */
    public void setCreateBy(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.create_by</code>. 创建者
     */
    public String getCreateBy() {
        return (String) get(18);
    }

    /**
     * Setter for <code>jeesite.sys_office.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>jeesite.sys_office.update_by</code>. 更新者
     */
    public void setUpdateBy(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.update_by</code>. 更新者
     */
    public String getUpdateBy() {
        return (String) get(20);
    }

    /**
     * Setter for <code>jeesite.sys_office.update_date</code>. 更新时间
     */
    public void setUpdateDate(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(21);
    }

    /**
     * Setter for <code>jeesite.sys_office.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(22);
    }

    /**
     * Setter for <code>jeesite.sys_office.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>jeesite.sys_office.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOfficeRecord
     */
    public SysOfficeRecord() {
        super(SysOffice.SYS_OFFICE);
    }

    /**
     * Create a detached, initialised SysOfficeRecord
     */
    public SysOfficeRecord(String id, String parentId, String parentIds, String name, Long sort, String areaId, String code, String type, String grade, String address, String zipCode, String master, String phone, String fax, String email, String useable, String primaryPerson, String deputyPerson, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate, String remarks, String delFlag) {
        super(SysOffice.SYS_OFFICE);

        set(0, id);
        set(1, parentId);
        set(2, parentIds);
        set(3, name);
        set(4, sort);
        set(5, areaId);
        set(6, code);
        set(7, type);
        set(8, grade);
        set(9, address);
        set(10, zipCode);
        set(11, master);
        set(12, phone);
        set(13, fax);
        set(14, email);
        set(15, useable);
        set(16, primaryPerson);
        set(17, deputyPerson);
        set(18, createBy);
        set(19, createDate);
        set(20, updateBy);
        set(21, updateDate);
        set(22, remarks);
        set(23, delFlag);
    }
}
