/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysOrganization;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOrganizationRecord extends UpdatableRecordImpl<SysOrganizationRecord> implements Record10<Long, String, String, String, Long, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1678478645;

    /**
     * Setter for <code>pms.sys_organization.id</code>. id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pms.sys_organization.id</code>. id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pms.sys_organization.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pms.sys_organization.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pms.sys_organization.parent_id</code>. 父级id
     */
    public void setParentId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pms.sys_organization.parent_id</code>. 父级id
     */
    public String getParentId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pms.sys_organization.parent_ids</code>. 所有父级id
     */
    public void setParentIds(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pms.sys_organization.parent_ids</code>. 所有父级id
     */
    public String getParentIds() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pms.sys_organization.area_id</code>. 区域id
     */
    public void setAreaId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pms.sys_organization.area_id</code>. 区域id
     */
    public Long getAreaId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>pms.sys_organization.type</code>. 类型
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pms.sys_organization.type</code>. 类型
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pms.sys_organization.level</code>. 级别
     */
    public void setLevel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pms.sys_organization.level</code>. 级别
     */
    public String getLevel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pms.sys_organization.gmt_create</code>.
     */
    public void setGmtCreate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>pms.sys_organization.gmt_create</code>.
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>pms.sys_organization.gmt_modified</code>.
     */
    public void setGmtModified(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>pms.sys_organization.gmt_modified</code>.
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>pms.sys_organization.def_flag</code>.
     */
    public void setDefFlag(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pms.sys_organization.def_flag</code>.
     */
    public String getDefFlag() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, Long, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, Long, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysOrganization.SYS_ORGANIZATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysOrganization.SYS_ORGANIZATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysOrganization.SYS_ORGANIZATION.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysOrganization.SYS_ORGANIZATION.PARENT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SysOrganization.SYS_ORGANIZATION.AREA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysOrganization.SYS_ORGANIZATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysOrganization.SYS_ORGANIZATION.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysOrganization.SYS_ORGANIZATION.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SysOrganization.SYS_ORGANIZATION.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysOrganization.SYS_ORGANIZATION.DEF_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAreaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDefFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAreaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDefFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value3(String value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value4(String value) {
        setParentIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value5(Long value) {
        setAreaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value6(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value7(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value8(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value9(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord value10(String value) {
        setDefFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysOrganizationRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, String value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysOrganizationRecord
     */
    public SysOrganizationRecord() {
        super(SysOrganization.SYS_ORGANIZATION);
    }

    /**
     * Create a detached, initialised SysOrganizationRecord
     */
    public SysOrganizationRecord(Long id, String name, String parentId, String parentIds, Long areaId, String type, String level, Timestamp gmtCreate, Timestamp gmtModified, String defFlag) {
        super(SysOrganization.SYS_ORGANIZATION);

        set(0, id);
        set(1, name);
        set(2, parentId);
        set(3, parentIds);
        set(4, areaId);
        set(5, type);
        set(6, level);
        set(7, gmtCreate);
        set(8, gmtModified);
        set(9, defFlag);
    }
}
