/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysRole;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements Record14<String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> {

    private static final long serialVersionUID = 1477478646;

    /**
     * Setter for <code>jeesite.sys_role.id</code>. 编号
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.id</code>. 编号
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_role.office_id</code>. 归属机构
     */
    public void setOfficeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.office_id</code>. 归属机构
     */
    public String getOfficeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jeesite.sys_role.name</code>. 角色名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.name</code>. 角色名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jeesite.sys_role.enname</code>. 英文名称
     */
    public void setEnname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.enname</code>. 英文名称
     */
    public String getEnname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jeesite.sys_role.role_type</code>. 角色类型
     */
    public void setRoleType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.role_type</code>. 角色类型
     */
    public String getRoleType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jeesite.sys_role.data_scope</code>. 数据范围
     */
    public void setDataScope(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.data_scope</code>. 数据范围
     */
    public String getDataScope() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jeesite.sys_role.is_sys</code>. 是否系统数据
     */
    public void setIsSys(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.is_sys</code>. 是否系统数据
     */
    public String getIsSys() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jeesite.sys_role.useable</code>. 是否可用
     */
    public void setUseable(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.useable</code>. 是否可用
     */
    public String getUseable() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jeesite.sys_role.create_by</code>. 创建者
     */
    public void setCreateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.create_by</code>. 创建者
     */
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jeesite.sys_role.create_date</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>jeesite.sys_role.update_by</code>. 更新者
     */
    public void setUpdateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.update_by</code>. 更新者
     */
    public String getUpdateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jeesite.sys_role.update_date</code>. 更新时间
     */
    public void setUpdateDate(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>jeesite.sys_role.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jeesite.sys_role.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>jeesite.sys_role.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysRole.SYS_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysRole.SYS_ROLE.OFFICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysRole.SYS_ROLE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysRole.SYS_ROLE.ENNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysRole.SYS_ROLE.ROLE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysRole.SYS_ROLE.DATA_SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysRole.SYS_ROLE.IS_SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysRole.SYS_ROLE.USEABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysRole.SYS_ROLE.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return SysRole.SYS_ROLE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysRole.SYS_ROLE.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return SysRole.SYS_ROLE.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SysRole.SYS_ROLE.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return SysRole.SYS_ROLE.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOfficeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEnname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRoleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDataScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIsSys();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUseable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOfficeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEnname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRoleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDataScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIsSys();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUseable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value2(String value) {
        setOfficeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value4(String value) {
        setEnname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value5(String value) {
        setRoleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value6(String value) {
        setDataScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value7(String value) {
        setIsSys(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value8(String value) {
        setUseable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value9(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value10(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value11(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value12(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value13(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value14(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Timestamp value10, String value11, Timestamp value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(String id, String officeId, String name, String enname, String roleType, String dataScope, String isSys, String useable, String createBy, Timestamp createDate, String updateBy, Timestamp updateDate, String remarks, String delFlag) {
        super(SysRole.SYS_ROLE);

        set(0, id);
        set(1, officeId);
        set(2, name);
        set(3, enname);
        set(4, roleType);
        set(5, dataScope);
        set(6, isSys);
        set(7, useable);
        set(8, createBy);
        set(9, createDate);
        set(10, updateBy);
        set(11, updateDate);
        set(12, remarks);
        set(13, delFlag);
    }
}
