/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysRoleOrg;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleOrgRecord extends UpdatableRecordImpl<SysRoleOrgRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1569650915;

    /**
     * Setter for <code>pms.sys_role_org.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pms.sys_role_org.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pms.sys_role_org.org_id</code>.
     */
    public void setOrgId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pms.sys_role_org.org_id</code>.
     */
    public Long getOrgId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysRoleOrg.SYS_ROLE_ORG.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SysRoleOrg.SYS_ROLE_ORG.ORG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOrgRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOrgRecord value2(Long value) {
        setOrgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOrgRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleOrgRecord
     */
    public SysRoleOrgRecord() {
        super(SysRoleOrg.SYS_ROLE_ORG);
    }

    /**
     * Create a detached, initialised SysRoleOrgRecord
     */
    public SysRoleOrgRecord(Long roleId, Long orgId) {
        super(SysRoleOrg.SYS_ROLE_ORG);

        set(0, roleId);
        set(1, orgId);
    }
}
