/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysRoleOffice;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色-机构
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleOfficeRecord extends UpdatableRecordImpl<SysRoleOfficeRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1139548873;

    /**
     * Setter for <code>jeesite.sys_role_office.role_id</code>. 角色编号
     */
    public void setRoleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jeesite.sys_role_office.role_id</code>. 角色编号
     */
    public String getRoleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jeesite.sys_role_office.office_id</code>. 机构编号
     */
    public void setOfficeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jeesite.sys_role_office.office_id</code>. 机构编号
     */
    public String getOfficeId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SysRoleOffice.SYS_ROLE_OFFICE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysRoleOffice.SYS_ROLE_OFFICE.OFFICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOfficeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOfficeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOfficeRecord value1(String value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOfficeRecord value2(String value) {
        setOfficeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleOfficeRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleOfficeRecord
     */
    public SysRoleOfficeRecord() {
        super(SysRoleOffice.SYS_ROLE_OFFICE);
    }

    /**
     * Create a detached, initialised SysRoleOfficeRecord
     */
    public SysRoleOfficeRecord(String roleId, String officeId) {
        super(SysRoleOffice.SYS_ROLE_OFFICE);

        set(0, roleId);
        set(1, officeId);
    }
}
