/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysRole;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements Record9<ULong, String, String, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 455260670;

    /**
     * Setter for <code>pms.sys_role.id</code>. 角色id
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>pms.sys_role.id</code>. 角色id
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>pms.sys_role.name</code>. 角色名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pms.sys_role.name</code>. 角色名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pms.sys_role.en_name</code>. 角色英文名
     */
    public void setEnName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pms.sys_role.en_name</code>. 角色英文名
     */
    public String getEnName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pms.sys_role.role_type</code>. 角色类型
     */
    public void setRoleType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pms.sys_role.role_type</code>. 角色类型
     */
    public String getRoleType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pms.sys_role.sort</code>. 排序号
     */
    public void setSort(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pms.sys_role.sort</code>. 排序号
     */
    public String getSort() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pms.sys_role.remarks</code>. 备注
     */
    public void setRemarks(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pms.sys_role.remarks</code>. 备注
     */
    public String getRemarks() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pms.sys_role.gmt_create</code>. 创建时间
     */
    public void setGmtCreate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pms.sys_role.gmt_create</code>. 创建时间
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pms.sys_role.gmt_modified</code>. 修改时间
     */
    public void setGmtModified(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>pms.sys_role.gmt_modified</code>. 修改时间
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>pms.sys_role.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pms.sys_role.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<ULong, String, String, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<ULong, String, String, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return SysRole.SYS_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysRole.SYS_ROLE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysRole.SYS_ROLE.EN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysRole.SYS_ROLE.ROLE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysRole.SYS_ROLE.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysRole.SYS_ROLE.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return SysRole.SYS_ROLE.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SysRole.SYS_ROLE.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysRole.SYS_ROLE.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRoleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEnName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRoleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value3(String value) {
        setEnName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value4(String value) {
        setRoleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value5(String value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value6(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value7(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value8(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value9(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord values(ULong value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(ULong id, String name, String enName, String roleType, String sort, String remarks, Timestamp gmtCreate, Timestamp gmtModified, String delFlag) {
        super(SysRole.SYS_ROLE);

        set(0, id);
        set(1, name);
        set(2, enName);
        set(3, roleType);
        set(4, sort);
        set(5, remarks);
        set(6, gmtCreate);
        set(7, gmtModified);
        set(8, delFlag);
    }
}
