/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysSystem;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysSystemRecord extends UpdatableRecordImpl<SysSystemRecord> implements Record7<Long, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 25876775;

    /**
     * Setter for <code>pms.sys_system.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pms.sys_system.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pms.sys_system.name</code>. 系统名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pms.sys_system.name</code>. 系统名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pms.sys_system.useable</code>. 时候启用
     */
    public void setUseable(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pms.sys_system.useable</code>. 时候启用
     */
    public String getUseable() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pms.sys_system.code</code>. 系统标识码
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pms.sys_system.code</code>. 系统标识码
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pms.sys_system.gmt_create</code>. 创建时间
     */
    public void setGmtCreate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>pms.sys_system.gmt_create</code>. 创建时间
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>pms.sys_system.gmt_modified</code>. 修改时间
     */
    public void setGmtModified(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pms.sys_system.gmt_modified</code>. 修改时间
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pms.sys_system.def_flag</code>. 删除标记
     */
    public void setDefFlag(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pms.sys_system.def_flag</code>. 删除标记
     */
    public String getDefFlag() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysSystem.SYS_SYSTEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysSystem.SYS_SYSTEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysSystem.SYS_SYSTEM.USEABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysSystem.SYS_SYSTEM.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SysSystem.SYS_SYSTEM.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return SysSystem.SYS_SYSTEM.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysSystem.SYS_SYSTEM.DEF_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUseable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDefFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUseable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDefFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value3(String value) {
        setUseable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value5(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value6(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord value7(String value) {
        setDefFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysSystemRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysSystemRecord
     */
    public SysSystemRecord() {
        super(SysSystem.SYS_SYSTEM);
    }

    /**
     * Create a detached, initialised SysSystemRecord
     */
    public SysSystemRecord(Long id, String name, String useable, String code, Timestamp gmtCreate, Timestamp gmtModified, String defFlag) {
        super(SysSystem.SYS_SYSTEM);

        set(0, id);
        set(1, name);
        set(2, useable);
        set(3, code);
        set(4, gmtCreate);
        set(5, gmtModified);
        set(6, defFlag);
    }
}
