/*
 * This file is generated by jOOQ.
 */
package com.yueya.system.dao.tables.records;


import com.yueya.system.dao.tables.SysUser;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements Record20<ULong, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = -936651574;

    /**
     * Setter for <code>pms.sys_user.id</code>. 编号
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>pms.sys_user.id</code>. 编号
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>pms.sys_user.user_code</code>. 用户标识码
     */
    public void setUserCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pms.sys_user.user_code</code>. 用户标识码
     */
    public String getUserCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pms.sys_user.organization_id</code>. 归属组织
     */
    public void setOrganizationId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pms.sys_user.organization_id</code>. 归属组织
     */
    public String getOrganizationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pms.sys_user.department_id</code>. 归属部门
     */
    public void setDepartmentId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pms.sys_user.department_id</code>. 归属部门
     */
    public String getDepartmentId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pms.sys_user.login_name</code>. 登录名
     */
    public void setLoginName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pms.sys_user.login_name</code>. 登录名
     */
    public String getLoginName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pms.sys_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pms.sys_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pms.sys_user.user_no</code>. 工号
     */
    public void setUserNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pms.sys_user.user_no</code>. 工号
     */
    public String getUserNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pms.sys_user.name</code>. 姓名
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pms.sys_user.name</code>. 姓名
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pms.sys_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pms.sys_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pms.sys_user.phone</code>. 电话
     */
    public void setPhone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>pms.sys_user.phone</code>. 电话
     */
    public String getPhone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pms.sys_user.mobile</code>. 手机
     */
    public void setMobile(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pms.sys_user.mobile</code>. 手机
     */
    public String getMobile() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pms.sys_user.user_type</code>. 用户类型
     */
    public void setUserType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pms.sys_user.user_type</code>. 用户类型
     */
    public String getUserType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pms.sys_user.photo</code>. 用户头像
     */
    public void setPhoto(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pms.sys_user.photo</code>. 用户头像
     */
    public String getPhoto() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pms.sys_user.login_ip</code>. 最后登陆IP
     */
    public void setLoginIp(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pms.sys_user.login_ip</code>. 最后登陆IP
     */
    public String getLoginIp() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pms.sys_user.login_date</code>. 最后登陆时间
     */
    public void setLoginDate(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>pms.sys_user.login_date</code>. 最后登陆时间
     */
    public Timestamp getLoginDate() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>pms.sys_user.login_flag</code>. 是否可登录
     */
    public void setLoginFlag(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>pms.sys_user.login_flag</code>. 是否可登录
     */
    public String getLoginFlag() {
        return (String) get(15);
    }

    /**
     * Setter for <code>pms.sys_user.gmt_create</code>. 创建时间
     */
    public void setGmtCreate(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>pms.sys_user.gmt_create</code>. 创建时间
     */
    public Timestamp getGmtCreate() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>pms.sys_user.gmt_modified</code>. 更新时间
     */
    public void setGmtModified(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>pms.sys_user.gmt_modified</code>. 更新时间
     */
    public Timestamp getGmtModified() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>pms.sys_user.remarks</code>. 备注信息
     */
    public void setRemarks(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>pms.sys_user.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(18);
    }

    /**
     * Setter for <code>pms.sys_user.del_flag</code>. 删除标记
     */
    public void setDelFlag(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>pms.sys_user.del_flag</code>. 删除标记
     */
    public String getDelFlag() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<ULong, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<ULong, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return SysUser.SYS_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysUser.SYS_USER.USER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysUser.SYS_USER.ORGANIZATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysUser.SYS_USER.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.LOGIN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysUser.SYS_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysUser.SYS_USER.USER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysUser.SYS_USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysUser.SYS_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysUser.SYS_USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysUser.SYS_USER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SysUser.SYS_USER.USER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SysUser.SYS_USER.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return SysUser.SYS_USER.LOGIN_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return SysUser.SYS_USER.LOGIN_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return SysUser.SYS_USER.LOGIN_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return SysUser.SYS_USER.GMT_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return SysUser.SYS_USER.GMT_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return SysUser.SYS_USER.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return SysUser.SYS_USER.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getLoginDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getLoginFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLoginName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getLoginDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getLoginFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getGmtCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getGmtModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value2(String value) {
        setUserCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value3(String value) {
        setOrganizationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value4(String value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value5(String value) {
        setLoginName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value6(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value7(String value) {
        setUserNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value8(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value9(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value10(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value11(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value12(String value) {
        setUserType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value13(String value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value14(String value) {
        setLoginIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value15(Timestamp value) {
        setLoginDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value16(String value) {
        setLoginFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value17(Timestamp value) {
        setGmtCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value18(Timestamp value) {
        setGmtModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value19(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value20(String value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord values(ULong value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, Timestamp value15, String value16, Timestamp value17, Timestamp value18, String value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(ULong id, String userCode, String organizationId, String departmentId, String loginName, String password, String userNo, String name, String email, String phone, String mobile, String userType, String photo, String loginIp, Timestamp loginDate, String loginFlag, Timestamp gmtCreate, Timestamp gmtModified, String remarks, String delFlag) {
        super(SysUser.SYS_USER);

        set(0, id);
        set(1, userCode);
        set(2, organizationId);
        set(3, departmentId);
        set(4, loginName);
        set(5, password);
        set(6, userNo);
        set(7, name);
        set(8, email);
        set(9, phone);
        set(10, mobile);
        set(11, userType);
        set(12, photo);
        set(13, loginIp);
        set(14, loginDate);
        set(15, loginFlag);
        set(16, gmtCreate);
        set(17, gmtModified);
        set(18, remarks);
        set(19, delFlag);
    }
}
